// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v3.21.12
// source: payment.proto

package payment

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	booking "handworks/common/grpc/booking"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type QuoteRequest struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Service       *booking.ServicesRequest `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	Addons        []*booking.AddOnRequest  `protobuf:"bytes,2,rep,name=addons,proto3" json:"addons,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuoteRequest) Reset() {
	*x = QuoteRequest{}
	mi := &file_payment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuoteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuoteRequest) ProtoMessage() {}

func (x *QuoteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuoteRequest.ProtoReflect.Descriptor instead.
func (*QuoteRequest) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{0}
}

func (x *QuoteRequest) GetService() *booking.ServicesRequest {
	if x != nil {
		return x.Service
	}
	return nil
}

func (x *QuoteRequest) GetAddons() []*booking.AddOnRequest {
	if x != nil {
		return x.Addons
	}
	return nil
}

type QuoteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AddonPrice    float32                `protobuf:"fixed32,1,opt,name=addon_price,json=addonPrice,proto3" json:"addon_price,omitempty"`
	Subtotal      float32                `protobuf:"fixed32,2,opt,name=subtotal,proto3" json:"subtotal,omitempty"`
	TotalPrice    float32                `protobuf:"fixed32,3,opt,name=total_price,json=totalPrice,proto3" json:"total_price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuoteResponse) Reset() {
	*x = QuoteResponse{}
	mi := &file_payment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuoteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuoteResponse) ProtoMessage() {}

func (x *QuoteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_payment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuoteResponse.ProtoReflect.Descriptor instead.
func (*QuoteResponse) Descriptor() ([]byte, []int) {
	return file_payment_proto_rawDescGZIP(), []int{1}
}

func (x *QuoteResponse) GetAddonPrice() float32 {
	if x != nil {
		return x.AddonPrice
	}
	return 0
}

func (x *QuoteResponse) GetSubtotal() float32 {
	if x != nil {
		return x.Subtotal
	}
	return 0
}

func (x *QuoteResponse) GetTotalPrice() float32 {
	if x != nil {
		return x.TotalPrice
	}
	return 0
}

var File_payment_proto protoreflect.FileDescriptor

const file_payment_proto_rawDesc = "" +
	"\n" +
	"\rpayment.proto\x1a\rbooking.proto\"a\n" +
	"\fQuoteRequest\x12*\n" +
	"\aservice\x18\x01 \x01(\v2\x10.ServicesRequestR\aservice\x12%\n" +
	"\x06addons\x18\x02 \x03(\v2\r.AddOnRequestR\x06addons\"m\n" +
	"\rQuoteResponse\x12\x1f\n" +
	"\vaddon_price\x18\x01 \x01(\x02R\n" +
	"addonPrice\x12\x1a\n" +
	"\bsubtotal\x18\x02 \x01(\x02R\bsubtotal\x12\x1f\n" +
	"\vtotal_price\x18\x03 \x01(\x02R\n" +
	"totalPrice2?\n" +
	"\x0ePaymentService\x12-\n" +
	"\fGetQuotation\x12\r.QuoteRequest\x1a\x0e.QuoteResponseB\x1fZ\x1dhandworks/common/grpc/paymentb\x06proto3"

var (
	file_payment_proto_rawDescOnce sync.Once
	file_payment_proto_rawDescData []byte
)

func file_payment_proto_rawDescGZIP() []byte {
	file_payment_proto_rawDescOnce.Do(func() {
		file_payment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_payment_proto_rawDesc), len(file_payment_proto_rawDesc)))
	})
	return file_payment_proto_rawDescData
}

var file_payment_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_payment_proto_goTypes = []any{
	(*QuoteRequest)(nil),            // 0: QuoteRequest
	(*QuoteResponse)(nil),           // 1: QuoteResponse
	(*booking.ServicesRequest)(nil), // 2: ServicesRequest
	(*booking.AddOnRequest)(nil),    // 3: AddOnRequest
}
var file_payment_proto_depIdxs = []int32{
	2, // 0: QuoteRequest.service:type_name -> ServicesRequest
	3, // 1: QuoteRequest.addons:type_name -> AddOnRequest
	0, // 2: PaymentService.GetQuotation:input_type -> QuoteRequest
	1, // 3: PaymentService.GetQuotation:output_type -> QuoteResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_payment_proto_init() }
func file_payment_proto_init() {
	if File_payment_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_payment_proto_rawDesc), len(file_payment_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_payment_proto_goTypes,
		DependencyIndexes: file_payment_proto_depIdxs,
		MessageInfos:      file_payment_proto_msgTypes,
	}.Build()
	File_payment_proto = out.File
	file_payment_proto_goTypes = nil
	file_payment_proto_depIdxs = nil
}
