run:
  timeout: 5m
  tests: true

linters:
  enable:
    - govet
    - staticcheck
    - gofmt
    - goimports
    - unused
    - errcheck
    - gosimple
    - ineffassign
    - gocyclo

linters-settings:
  gocyclo:
    min-complexity: 15

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
