package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.78

import (
	"context"
	"fmt"
	"handworks-gateway/graph/generated/models"
	"handworks-gateway/graph/resolvers/helpers"
	"handworks/common/grpc/booking"
)

// CreateBooking is the resolver for the createBooking field.
func (r *mutationResolver) CreateBooking(ctx context.Context, input models.CreateBookingInput) (*models.Booking, error) {
	baseReq := helpers.MapBaseDetailsInputToProto(input.Base)
	req := &booking.CreateBookingRequest{
		Base:        baseReq,
		MainService: helpers.MapServicesInput(input.MainService),
		Addons:      helpers.MapAddOnInputs(input.Addons),
	}
	res, err := r.GrpcClients.BookingClient.CreateBooking(ctx, req)
	if err != nil {
		r.Log.Error("Failed to dial booking rpc: %s", err)
	}
	return helpers.MapBooking(res.Book), nil
}

// unimplemented pa ni sila cuz idk pa sa kang clarence if final na ba to iyaha
// UpdateBooking is the resolver for the updateBooking field.
func (r *mutationResolver) UpdateBooking(ctx context.Context, input models.CreateBookingInput) (*models.Booking, error) {
	panic(fmt.Errorf("not implemented: UpdateBooking - updateBooking"))
}

// DeleteBooking is the resolver for the deleteBooking field.
func (r *mutationResolver) DeleteBooking(ctx context.Context, bookingID string) (bool, error) {
	panic(fmt.Errorf("not implemented: DeleteBooking - deleteBooking"))
}

// GetBookingByID is the resolver for the getBookingById field.
func (r *queryResolver) GetBookingByID(ctx context.Context, bookingID string) (*models.Booking, error) {
	panic(fmt.Errorf("not implemented: GetBookingByID - getBookingById"))
}

// GetBookingByUID is the resolver for the getBookingByUId field.
func (r *queryResolver) GetBookingByUID(ctx context.Context, userID string) ([]*models.Booking, error) {
	panic(fmt.Errorf("not implemented: GetBookingByUID - getBookingByUId"))
}
