// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: booking.proto

package booking

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BookingType int32

const (
	BookingType_GENERAL           BookingType = 0
	BookingType_COUCH             BookingType = 1
	BookingType_SOFA              BookingType = 2
	BookingType_CARPET            BookingType = 3
	BookingType_MATRESS           BookingType = 4
	BookingType_CAR_INTERIOR      BookingType = 5
	BookingType_POST_CONSTRUCTION BookingType = 6
)

// Enum value maps for BookingType.
var (
	BookingType_name = map[int32]string{
		0: "GENERAL",
		1: "COUCH",
		2: "SOFA",
		3: "CARPET",
		4: "MATRESS",
		5: "CAR_INTERIOR",
		6: "POST_CONSTRUCTION",
	}
	BookingType_value = map[string]int32{
		"GENERAL":           0,
		"COUCH":             1,
		"SOFA":              2,
		"CARPET":            3,
		"MATRESS":           4,
		"CAR_INTERIOR":      5,
		"POST_CONSTRUCTION": 6,
	}
)

func (x BookingType) Enum() *BookingType {
	p := new(BookingType)
	*p = x
	return p
}

func (x BookingType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BookingType) Descriptor() protoreflect.EnumDescriptor {
	return file_booking_proto_enumTypes[0].Descriptor()
}

func (BookingType) Type() protoreflect.EnumType {
	return &file_booking_proto_enumTypes[0]
}

func (x BookingType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BookingType.Descriptor instead.
func (BookingType) EnumDescriptor() ([]byte, []int) {
	return file_booking_proto_rawDescGZIP(), []int{0}
}

type Status int32

const (
	Status_PENDING   Status = 0
	Status_CONFIRMED Status = 1
	Status_CANCELLED Status = 2
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "PENDING",
		1: "CONFIRMED",
		2: "CANCELLED",
	}
	Status_value = map[string]int32{
		"PENDING":   0,
		"CONFIRMED": 1,
		"CANCELLED": 2,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_booking_proto_enumTypes[1].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_booking_proto_enumTypes[1]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_booking_proto_rawDescGZIP(), []int{1}
}

type Booking struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CustomerId    string                 `protobuf:"bytes,2,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	AddressId     string                 `protobuf:"bytes,3,opt,name=address_id,json=addressId,proto3" json:"address_id,omitempty"`
	BookingType   BookingType            `protobuf:"varint,4,opt,name=booking_type,json=bookingType,proto3,enum=BookingType" json:"booking_type,omitempty"`
	DirtyScale    int32                  `protobuf:"varint,5,opt,name=dirty_scale,json=dirtyScale,proto3" json:"dirty_scale,omitempty"`
	Schedule      *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=schedule,proto3" json:"schedule,omitempty"`
	Status        Status                 `protobuf:"varint,7,opt,name=status,proto3,enum=Status" json:"status,omitempty"`
	Notes         string                 `protobuf:"bytes,8,opt,name=notes,proto3" json:"notes,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Booking) Reset() {
	*x = Booking{}
	mi := &file_booking_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Booking) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Booking) ProtoMessage() {}

func (x *Booking) ProtoReflect() protoreflect.Message {
	mi := &file_booking_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Booking.ProtoReflect.Descriptor instead.
func (*Booking) Descriptor() ([]byte, []int) {
	return file_booking_proto_rawDescGZIP(), []int{0}
}

func (x *Booking) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Booking) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *Booking) GetAddressId() string {
	if x != nil {
		return x.AddressId
	}
	return ""
}

func (x *Booking) GetBookingType() BookingType {
	if x != nil {
		return x.BookingType
	}
	return BookingType_GENERAL
}

func (x *Booking) GetDirtyScale() int32 {
	if x != nil {
		return x.DirtyScale
	}
	return 0
}

func (x *Booking) GetSchedule() *timestamppb.Timestamp {
	if x != nil {
		return x.Schedule
	}
	return nil
}

func (x *Booking) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_PENDING
}

func (x *Booking) GetNotes() string {
	if x != nil {
		return x.Notes
	}
	return ""
}

func (x *Booking) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Booking) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type CreateBookRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CustomerId    string                 `protobuf:"bytes,1,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	AddressId     string                 `protobuf:"bytes,2,opt,name=address_id,json=addressId,proto3" json:"address_id,omitempty"`
	BookingType   BookingType            `protobuf:"varint,3,opt,name=booking_type,json=bookingType,proto3,enum=BookingType" json:"booking_type,omitempty"`
	DirtyScale    int32                  `protobuf:"varint,4,opt,name=dirty_scale,json=dirtyScale,proto3" json:"dirty_scale,omitempty"`
	Schedule      *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=schedule,proto3" json:"schedule,omitempty"`
	Status        Status                 `protobuf:"varint,6,opt,name=status,proto3,enum=Status" json:"status,omitempty"`
	Notes         string                 `protobuf:"bytes,7,opt,name=notes,proto3" json:"notes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBookRequest) Reset() {
	*x = CreateBookRequest{}
	mi := &file_booking_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBookRequest) ProtoMessage() {}

func (x *CreateBookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_booking_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBookRequest.ProtoReflect.Descriptor instead.
func (*CreateBookRequest) Descriptor() ([]byte, []int) {
	return file_booking_proto_rawDescGZIP(), []int{1}
}

func (x *CreateBookRequest) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *CreateBookRequest) GetAddressId() string {
	if x != nil {
		return x.AddressId
	}
	return ""
}

func (x *CreateBookRequest) GetBookingType() BookingType {
	if x != nil {
		return x.BookingType
	}
	return BookingType_GENERAL
}

func (x *CreateBookRequest) GetDirtyScale() int32 {
	if x != nil {
		return x.DirtyScale
	}
	return 0
}

func (x *CreateBookRequest) GetSchedule() *timestamppb.Timestamp {
	if x != nil {
		return x.Schedule
	}
	return nil
}

func (x *CreateBookRequest) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_PENDING
}

func (x *CreateBookRequest) GetNotes() string {
	if x != nil {
		return x.Notes
	}
	return ""
}

type CreateBookResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Book          *Booking               `protobuf:"bytes,1,opt,name=book,proto3" json:"book,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBookResponse) Reset() {
	*x = CreateBookResponse{}
	mi := &file_booking_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBookResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBookResponse) ProtoMessage() {}

func (x *CreateBookResponse) ProtoReflect() protoreflect.Message {
	mi := &file_booking_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBookResponse.ProtoReflect.Descriptor instead.
func (*CreateBookResponse) Descriptor() ([]byte, []int) {
	return file_booking_proto_rawDescGZIP(), []int{2}
}

func (x *CreateBookResponse) GetBook() *Booking {
	if x != nil {
		return x.Book
	}
	return nil
}

type GetBooksByUIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CustomerId    string                 `protobuf:"bytes,1,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBooksByUIDRequest) Reset() {
	*x = GetBooksByUIDRequest{}
	mi := &file_booking_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBooksByUIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBooksByUIDRequest) ProtoMessage() {}

func (x *GetBooksByUIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_booking_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBooksByUIDRequest.ProtoReflect.Descriptor instead.
func (*GetBooksByUIDRequest) Descriptor() ([]byte, []int) {
	return file_booking_proto_rawDescGZIP(), []int{3}
}

func (x *GetBooksByUIDRequest) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

type GetBooksByUIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Books         []*Booking             `protobuf:"bytes,1,rep,name=books,proto3" json:"books,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBooksByUIDResponse) Reset() {
	*x = GetBooksByUIDResponse{}
	mi := &file_booking_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBooksByUIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBooksByUIDResponse) ProtoMessage() {}

func (x *GetBooksByUIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_booking_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBooksByUIDResponse.ProtoReflect.Descriptor instead.
func (*GetBooksByUIDResponse) Descriptor() ([]byte, []int) {
	return file_booking_proto_rawDescGZIP(), []int{4}
}

func (x *GetBooksByUIDResponse) GetBooks() []*Booking {
	if x != nil {
		return x.Books
	}
	return nil
}

func (x *GetBooksByUIDResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type UpdateBookRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CustomerId    string                 `protobuf:"bytes,2,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	AddressId     string                 `protobuf:"bytes,3,opt,name=address_id,json=addressId,proto3" json:"address_id,omitempty"`
	BookingType   BookingType            `protobuf:"varint,4,opt,name=booking_type,json=bookingType,proto3,enum=BookingType" json:"booking_type,omitempty"`
	DirtyScale    int32                  `protobuf:"varint,5,opt,name=dirty_scale,json=dirtyScale,proto3" json:"dirty_scale,omitempty"`
	Schedule      *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=schedule,proto3" json:"schedule,omitempty"`
	Status        Status                 `protobuf:"varint,7,opt,name=status,proto3,enum=Status" json:"status,omitempty"`
	Notes         string                 `protobuf:"bytes,8,opt,name=notes,proto3" json:"notes,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateBookRequest) Reset() {
	*x = UpdateBookRequest{}
	mi := &file_booking_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateBookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBookRequest) ProtoMessage() {}

func (x *UpdateBookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_booking_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBookRequest.ProtoReflect.Descriptor instead.
func (*UpdateBookRequest) Descriptor() ([]byte, []int) {
	return file_booking_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateBookRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateBookRequest) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *UpdateBookRequest) GetAddressId() string {
	if x != nil {
		return x.AddressId
	}
	return ""
}

func (x *UpdateBookRequest) GetBookingType() BookingType {
	if x != nil {
		return x.BookingType
	}
	return BookingType_GENERAL
}

func (x *UpdateBookRequest) GetDirtyScale() int32 {
	if x != nil {
		return x.DirtyScale
	}
	return 0
}

func (x *UpdateBookRequest) GetSchedule() *timestamppb.Timestamp {
	if x != nil {
		return x.Schedule
	}
	return nil
}

func (x *UpdateBookRequest) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_PENDING
}

func (x *UpdateBookRequest) GetNotes() string {
	if x != nil {
		return x.Notes
	}
	return ""
}

func (x *UpdateBookRequest) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type UpdateBookResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Book          *Booking               `protobuf:"bytes,1,opt,name=book,proto3" json:"book,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateBookResponse) Reset() {
	*x = UpdateBookResponse{}
	mi := &file_booking_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateBookResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBookResponse) ProtoMessage() {}

func (x *UpdateBookResponse) ProtoReflect() protoreflect.Message {
	mi := &file_booking_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBookResponse.ProtoReflect.Descriptor instead.
func (*UpdateBookResponse) Descriptor() ([]byte, []int) {
	return file_booking_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateBookResponse) GetBook() *Booking {
	if x != nil {
		return x.Book
	}
	return nil
}

type DeleteBookRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteBookRequest) Reset() {
	*x = DeleteBookRequest{}
	mi := &file_booking_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteBookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBookRequest) ProtoMessage() {}

func (x *DeleteBookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_booking_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBookRequest.ProtoReflect.Descriptor instead.
func (*DeleteBookRequest) Descriptor() ([]byte, []int) {
	return file_booking_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteBookRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteBookResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteBookResponse) Reset() {
	*x = DeleteBookResponse{}
	mi := &file_booking_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteBookResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBookResponse) ProtoMessage() {}

func (x *DeleteBookResponse) ProtoReflect() protoreflect.Message {
	mi := &file_booking_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBookResponse.ProtoReflect.Descriptor instead.
func (*DeleteBookResponse) Descriptor() ([]byte, []int) {
	return file_booking_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteBookResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DeleteBookResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_booking_proto protoreflect.FileDescriptor

const file_booking_proto_rawDesc = "" +
	"\n" +
	"\rbooking.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x90\x03\n" +
	"\aBooking\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vcustomer_id\x18\x02 \x01(\tR\n" +
	"customerId\x12\x1d\n" +
	"\n" +
	"address_id\x18\x03 \x01(\tR\taddressId\x12/\n" +
	"\fbooking_type\x18\x04 \x01(\x0e2\f.BookingTypeR\vbookingType\x12\x1f\n" +
	"\vdirty_scale\x18\x05 \x01(\x05R\n" +
	"dirtyScale\x126\n" +
	"\bschedule\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\bschedule\x12\x1f\n" +
	"\x06status\x18\a \x01(\x0e2\a.StatusR\x06status\x12\x14\n" +
	"\x05notes\x18\b \x01(\tR\x05notes\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\x94\x02\n" +
	"\x11CreateBookRequest\x12\x1f\n" +
	"\vcustomer_id\x18\x01 \x01(\tR\n" +
	"customerId\x12\x1d\n" +
	"\n" +
	"address_id\x18\x02 \x01(\tR\taddressId\x12/\n" +
	"\fbooking_type\x18\x03 \x01(\x0e2\f.BookingTypeR\vbookingType\x12\x1f\n" +
	"\vdirty_scale\x18\x04 \x01(\x05R\n" +
	"dirtyScale\x126\n" +
	"\bschedule\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\bschedule\x12\x1f\n" +
	"\x06status\x18\x06 \x01(\x0e2\a.StatusR\x06status\x12\x14\n" +
	"\x05notes\x18\a \x01(\tR\x05notes\"2\n" +
	"\x12CreateBookResponse\x12\x1c\n" +
	"\x04book\x18\x01 \x01(\v2\b.BookingR\x04book\"7\n" +
	"\x14GetBooksByUIDRequest\x12\x1f\n" +
	"\vcustomer_id\x18\x01 \x01(\tR\n" +
	"customerId\"Q\n" +
	"\x15GetBooksByUIDResponse\x12\x1e\n" +
	"\x05books\x18\x01 \x03(\v2\b.BookingR\x05books\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xdf\x02\n" +
	"\x11UpdateBookRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vcustomer_id\x18\x02 \x01(\tR\n" +
	"customerId\x12\x1d\n" +
	"\n" +
	"address_id\x18\x03 \x01(\tR\taddressId\x12/\n" +
	"\fbooking_type\x18\x04 \x01(\x0e2\f.BookingTypeR\vbookingType\x12\x1f\n" +
	"\vdirty_scale\x18\x05 \x01(\x05R\n" +
	"dirtyScale\x126\n" +
	"\bschedule\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\bschedule\x12\x1f\n" +
	"\x06status\x18\a \x01(\x0e2\a.StatusR\x06status\x12\x14\n" +
	"\x05notes\x18\b \x01(\tR\x05notes\x129\n" +
	"\n" +
	"updated_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"2\n" +
	"\x12UpdateBookResponse\x12\x1c\n" +
	"\x04book\x18\x01 \x01(\v2\b.BookingR\x04book\"#\n" +
	"\x11DeleteBookRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\">\n" +
	"\x12DeleteBookResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage*q\n" +
	"\vBookingType\x12\v\n" +
	"\aGENERAL\x10\x00\x12\t\n" +
	"\x05COUCH\x10\x01\x12\b\n" +
	"\x04SOFA\x10\x02\x12\n" +
	"\n" +
	"\x06CARPET\x10\x03\x12\v\n" +
	"\aMATRESS\x10\x04\x12\x10\n" +
	"\fCAR_INTERIOR\x10\x05\x12\x15\n" +
	"\x11POST_CONSTRUCTION\x10\x06*3\n" +
	"\x06Status\x12\v\n" +
	"\aPENDING\x10\x00\x12\r\n" +
	"\tCONFIRMED\x10\x01\x12\r\n" +
	"\tCANCELLED\x10\x022\xf5\x01\n" +
	"\x0eBookingService\x125\n" +
	"\n" +
	"CreateBook\x12\x12.CreateBookRequest\x1a\x13.CreateBookResponse\x12>\n" +
	"\rGetBooksByUID\x12\x15.GetBooksByUIDRequest\x1a\x16.GetBooksByUIDResponse\x125\n" +
	"\n" +
	"UpdateBook\x12\x12.UpdateBookRequest\x1a\x13.UpdateBookResponse\x125\n" +
	"\n" +
	"DeleteBook\x12\x12.DeleteBookRequest\x1a\x13.DeleteBookResponseB\x1fZ\x1dhandworks/common/grpc/bookingb\x06proto3"

var (
	file_booking_proto_rawDescOnce sync.Once
	file_booking_proto_rawDescData []byte
)

func file_booking_proto_rawDescGZIP() []byte {
	file_booking_proto_rawDescOnce.Do(func() {
		file_booking_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_booking_proto_rawDesc), len(file_booking_proto_rawDesc)))
	})
	return file_booking_proto_rawDescData
}

var file_booking_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_booking_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_booking_proto_goTypes = []any{
	(BookingType)(0),              // 0: BookingType
	(Status)(0),                   // 1: Status
	(*Booking)(nil),               // 2: Booking
	(*CreateBookRequest)(nil),     // 3: CreateBookRequest
	(*CreateBookResponse)(nil),    // 4: CreateBookResponse
	(*GetBooksByUIDRequest)(nil),  // 5: GetBooksByUIDRequest
	(*GetBooksByUIDResponse)(nil), // 6: GetBooksByUIDResponse
	(*UpdateBookRequest)(nil),     // 7: UpdateBookRequest
	(*UpdateBookResponse)(nil),    // 8: UpdateBookResponse
	(*DeleteBookRequest)(nil),     // 9: DeleteBookRequest
	(*DeleteBookResponse)(nil),    // 10: DeleteBookResponse
	(*timestamppb.Timestamp)(nil), // 11: google.protobuf.Timestamp
}
var file_booking_proto_depIdxs = []int32{
	0,  // 0: Booking.booking_type:type_name -> BookingType
	11, // 1: Booking.schedule:type_name -> google.protobuf.Timestamp
	1,  // 2: Booking.status:type_name -> Status
	11, // 3: Booking.created_at:type_name -> google.protobuf.Timestamp
	11, // 4: Booking.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 5: CreateBookRequest.booking_type:type_name -> BookingType
	11, // 6: CreateBookRequest.schedule:type_name -> google.protobuf.Timestamp
	1,  // 7: CreateBookRequest.status:type_name -> Status
	2,  // 8: CreateBookResponse.book:type_name -> Booking
	2,  // 9: GetBooksByUIDResponse.books:type_name -> Booking
	0,  // 10: UpdateBookRequest.booking_type:type_name -> BookingType
	11, // 11: UpdateBookRequest.schedule:type_name -> google.protobuf.Timestamp
	1,  // 12: UpdateBookRequest.status:type_name -> Status
	11, // 13: UpdateBookRequest.updated_at:type_name -> google.protobuf.Timestamp
	2,  // 14: UpdateBookResponse.book:type_name -> Booking
	3,  // 15: BookingService.CreateBook:input_type -> CreateBookRequest
	5,  // 16: BookingService.GetBooksByUID:input_type -> GetBooksByUIDRequest
	7,  // 17: BookingService.UpdateBook:input_type -> UpdateBookRequest
	9,  // 18: BookingService.DeleteBook:input_type -> DeleteBookRequest
	4,  // 19: BookingService.CreateBook:output_type -> CreateBookResponse
	6,  // 20: BookingService.GetBooksByUID:output_type -> GetBooksByUIDResponse
	8,  // 21: BookingService.UpdateBook:output_type -> UpdateBookResponse
	10, // 22: BookingService.DeleteBook:output_type -> DeleteBookResponse
	19, // [19:23] is the sub-list for method output_type
	15, // [15:19] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_booking_proto_init() }
func file_booking_proto_init() {
	if File_booking_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_booking_proto_rawDesc), len(file_booking_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_booking_proto_goTypes,
		DependencyIndexes: file_booking_proto_depIdxs,
		EnumInfos:         file_booking_proto_enumTypes,
		MessageInfos:      file_booking_proto_msgTypes,
	}.Build()
	File_booking_proto = out.File
	file_booking_proto_goTypes = nil
	file_booking_proto_depIdxs = nil
}
