// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: booking.proto

package booking

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MainServiceType int32

const (
	MainServiceType_SERVICE_TYPE_UNSPECIFIED MainServiceType = 0
	MainServiceType_GENERAL                  MainServiceType = 1
	MainServiceType_COUCH                    MainServiceType = 2
	MainServiceType_MATTRESS                 MainServiceType = 3
	MainServiceType_CAR                      MainServiceType = 4
	MainServiceType_POST                     MainServiceType = 5
)

// Enum value maps for MainServiceType.
var (
	MainServiceType_name = map[int32]string{
		0: "SERVICE_TYPE_UNSPECIFIED",
		1: "GENERAL",
		2: "COUCH",
		3: "MATTRESS",
		4: "CAR",
		5: "POST",
	}
	MainServiceType_value = map[string]int32{
		"SERVICE_TYPE_UNSPECIFIED": 0,
		"GENERAL":                  1,
		"COUCH":                    2,
		"MATTRESS":                 3,
		"CAR":                      4,
		"POST":                     5,
	}
)

func (x MainServiceType) Enum() *MainServiceType {
	p := new(MainServiceType)
	*p = x
	return p
}

func (x MainServiceType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MainServiceType) Descriptor() protoreflect.EnumDescriptor {
	return file_booking_proto_enumTypes[0].Descriptor()
}

func (MainServiceType) Type() protoreflect.EnumType {
	return &file_booking_proto_enumTypes[0]
}

func (x MainServiceType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MainServiceType.Descriptor instead.
func (MainServiceType) EnumDescriptor() ([]byte, []int) {
	return file_booking_proto_rawDescGZIP(), []int{0}
}

type HomeType int32

const (
	HomeType_CONDO_ROOM HomeType = 0
	HomeType_HOUSE      HomeType = 1
	HomeType_COMMERCIAL HomeType = 2
)

// Enum value maps for HomeType.
var (
	HomeType_name = map[int32]string{
		0: "CONDO_ROOM",
		1: "HOUSE",
		2: "COMMERCIAL",
	}
	HomeType_value = map[string]int32{
		"CONDO_ROOM": 0,
		"HOUSE":      1,
		"COMMERCIAL": 2,
	}
)

func (x HomeType) Enum() *HomeType {
	p := new(HomeType)
	*p = x
	return p
}

func (x HomeType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HomeType) Descriptor() protoreflect.EnumDescriptor {
	return file_booking_proto_enumTypes[1].Descriptor()
}

func (HomeType) Type() protoreflect.EnumType {
	return &file_booking_proto_enumTypes[1]
}

func (x HomeType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HomeType.Descriptor instead.
func (HomeType) EnumDescriptor() ([]byte, []int) {
	return file_booking_proto_rawDescGZIP(), []int{1}
}

type CouchType int32

const (
	CouchType_SEATER_1             CouchType = 0
	CouchType_SEATER_2             CouchType = 1
	CouchType_SEATER_3             CouchType = 2
	CouchType_SEATER_3_LTYPE_SMALL CouchType = 3
	CouchType_SEATER_3_LTYPE_LARGE CouchType = 4
	CouchType_SEATER_4_LTYPE_SMALL CouchType = 5
	CouchType_SEATER_4_LTYPE_LARGE CouchType = 6
	CouchType_SEATER_5_LTYPE       CouchType = 7
	CouchType_SEATER_6_LTYPE       CouchType = 8
	CouchType_OTTOMAN              CouchType = 9
	CouchType_LAZBOY               CouchType = 10
	CouchType_CHAIR                CouchType = 11
)

// Enum value maps for CouchType.
var (
	CouchType_name = map[int32]string{
		0:  "SEATER_1",
		1:  "SEATER_2",
		2:  "SEATER_3",
		3:  "SEATER_3_LTYPE_SMALL",
		4:  "SEATER_3_LTYPE_LARGE",
		5:  "SEATER_4_LTYPE_SMALL",
		6:  "SEATER_4_LTYPE_LARGE",
		7:  "SEATER_5_LTYPE",
		8:  "SEATER_6_LTYPE",
		9:  "OTTOMAN",
		10: "LAZBOY",
		11: "CHAIR",
	}
	CouchType_value = map[string]int32{
		"SEATER_1":             0,
		"SEATER_2":             1,
		"SEATER_3":             2,
		"SEATER_3_LTYPE_SMALL": 3,
		"SEATER_3_LTYPE_LARGE": 4,
		"SEATER_4_LTYPE_SMALL": 5,
		"SEATER_4_LTYPE_LARGE": 6,
		"SEATER_5_LTYPE":       7,
		"SEATER_6_LTYPE":       8,
		"OTTOMAN":              9,
		"LAZBOY":               10,
		"CHAIR":                11,
	}
)

func (x CouchType) Enum() *CouchType {
	p := new(CouchType)
	*p = x
	return p
}

func (x CouchType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CouchType) Descriptor() protoreflect.EnumDescriptor {
	return file_booking_proto_enumTypes[2].Descriptor()
}

func (CouchType) Type() protoreflect.EnumType {
	return &file_booking_proto_enumTypes[2]
}

func (x CouchType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CouchType.Descriptor instead.
func (CouchType) EnumDescriptor() ([]byte, []int) {
	return file_booking_proto_rawDescGZIP(), []int{2}
}

type BedType int32

const (
	BedType_KING           BedType = 0
	BedType_QUEEN          BedType = 1
	BedType_KING_HEADBAND  BedType = 2
	BedType_QUEEN_HEADBAND BedType = 3
	BedType_DOUBLE         BedType = 4
	BedType_SINGLE         BedType = 5
	BedType_BED_PILLOW     BedType = 6
)

// Enum value maps for BedType.
var (
	BedType_name = map[int32]string{
		0: "KING",
		1: "QUEEN",
		2: "KING_HEADBAND",
		3: "QUEEN_HEADBAND",
		4: "DOUBLE",
		5: "SINGLE",
		6: "BED_PILLOW",
	}
	BedType_value = map[string]int32{
		"KING":           0,
		"QUEEN":          1,
		"KING_HEADBAND":  2,
		"QUEEN_HEADBAND": 3,
		"DOUBLE":         4,
		"SINGLE":         5,
		"BED_PILLOW":     6,
	}
)

func (x BedType) Enum() *BedType {
	p := new(BedType)
	*p = x
	return p
}

func (x BedType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BedType) Descriptor() protoreflect.EnumDescriptor {
	return file_booking_proto_enumTypes[3].Descriptor()
}

func (BedType) Type() protoreflect.EnumType {
	return &file_booking_proto_enumTypes[3]
}

func (x BedType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BedType.Descriptor instead.
func (BedType) EnumDescriptor() ([]byte, []int) {
	return file_booking_proto_rawDescGZIP(), []int{3}
}

type CarType int32

const (
	CarType_SEDAN     CarType = 0
	CarType_MPV       CarType = 1
	CarType_SUV       CarType = 2
	CarType_PICKUP    CarType = 3
	CarType_VAN       CarType = 4
	CarType_CAR_SMALL CarType = 5
)

// Enum value maps for CarType.
var (
	CarType_name = map[int32]string{
		0: "SEDAN",
		1: "MPV",
		2: "SUV",
		3: "PICKUP",
		4: "VAN",
		5: "CAR_SMALL",
	}
	CarType_value = map[string]int32{
		"SEDAN":     0,
		"MPV":       1,
		"SUV":       2,
		"PICKUP":    3,
		"VAN":       4,
		"CAR_SMALL": 5,
	}
)

func (x CarType) Enum() *CarType {
	p := new(CarType)
	*p = x
	return p
}

func (x CarType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CarType) Descriptor() protoreflect.EnumDescriptor {
	return file_booking_proto_enumTypes[4].Descriptor()
}

func (CarType) Type() protoreflect.EnumType {
	return &file_booking_proto_enumTypes[4]
}

func (x CarType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CarType.Descriptor instead.
func (CarType) EnumDescriptor() ([]byte, []int) {
	return file_booking_proto_rawDescGZIP(), []int{4}
}

type Address struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AddressHuman  string                 `protobuf:"bytes,1,opt,name=address_human,json=addressHuman,proto3" json:"address_human,omitempty"`
	AddressLat    float64                `protobuf:"fixed64,2,opt,name=address_lat,json=addressLat,proto3" json:"address_lat,omitempty"`
	AddressLng    float64                `protobuf:"fixed64,3,opt,name=address_lng,json=addressLng,proto3" json:"address_lng,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Address) Reset() {
	*x = Address{}
	mi := &file_booking_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Address) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Address) ProtoMessage() {}

func (x *Address) ProtoReflect() protoreflect.Message {
	mi := &file_booking_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Address.ProtoReflect.Descriptor instead.
func (*Address) Descriptor() ([]byte, []int) {
	return file_booking_proto_rawDescGZIP(), []int{0}
}

func (x *Address) GetAddressHuman() string {
	if x != nil {
		return x.AddressHuman
	}
	return ""
}

func (x *Address) GetAddressLat() float64 {
	if x != nil {
		return x.AddressLat
	}
	return 0
}

func (x *Address) GetAddressLng() float64 {
	if x != nil {
		return x.AddressLng
	}
	return 0
}

type CleaningEquipment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	PhotoUrl      string                 `protobuf:"bytes,4,opt,name=photo_url,json=photoUrl,proto3" json:"photo_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CleaningEquipment) Reset() {
	*x = CleaningEquipment{}
	mi := &file_booking_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CleaningEquipment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CleaningEquipment) ProtoMessage() {}

func (x *CleaningEquipment) ProtoReflect() protoreflect.Message {
	mi := &file_booking_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CleaningEquipment.ProtoReflect.Descriptor instead.
func (*CleaningEquipment) Descriptor() ([]byte, []int) {
	return file_booking_proto_rawDescGZIP(), []int{1}
}

func (x *CleaningEquipment) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CleaningEquipment) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CleaningEquipment) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CleaningEquipment) GetPhotoUrl() string {
	if x != nil {
		return x.PhotoUrl
	}
	return ""
}

type CleaningResources struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	PhotoUrl      string                 `protobuf:"bytes,4,opt,name=photo_url,json=photoUrl,proto3" json:"photo_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CleaningResources) Reset() {
	*x = CleaningResources{}
	mi := &file_booking_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CleaningResources) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CleaningResources) ProtoMessage() {}

func (x *CleaningResources) ProtoReflect() protoreflect.Message {
	mi := &file_booking_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CleaningResources.ProtoReflect.Descriptor instead.
func (*CleaningResources) Descriptor() ([]byte, []int) {
	return file_booking_proto_rawDescGZIP(), []int{2}
}

func (x *CleaningResources) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CleaningResources) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CleaningResources) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CleaningResources) GetPhotoUrl() string {
	if x != nil {
		return x.PhotoUrl
	}
	return ""
}

type CleanerAssigned struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CleanerFirstName string                 `protobuf:"bytes,2,opt,name=cleaner_first_name,json=cleanerFirstName,proto3" json:"cleaner_first_name,omitempty"`
	CleanerLastName  string                 `protobuf:"bytes,3,opt,name=cleaner_last_name,json=cleanerLastName,proto3" json:"cleaner_last_name,omitempty"`
	PfpUrl           string                 `protobuf:"bytes,4,opt,name=pfp_url,json=pfpUrl,proto3" json:"pfp_url,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CleanerAssigned) Reset() {
	*x = CleanerAssigned{}
	mi := &file_booking_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CleanerAssigned) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CleanerAssigned) ProtoMessage() {}

func (x *CleanerAssigned) ProtoReflect() protoreflect.Message {
	mi := &file_booking_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CleanerAssigned.ProtoReflect.Descriptor instead.
func (*CleanerAssigned) Descriptor() ([]byte, []int) {
	return file_booking_proto_rawDescGZIP(), []int{3}
}

func (x *CleanerAssigned) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CleanerAssigned) GetCleanerFirstName() string {
	if x != nil {
		return x.CleanerFirstName
	}
	return ""
}

func (x *CleanerAssigned) GetCleanerLastName() string {
	if x != nil {
		return x.CleanerLastName
	}
	return ""
}

func (x *CleanerAssigned) GetPfpUrl() string {
	if x != nil {
		return x.PfpUrl
	}
	return ""
}

type ServiceDetail struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Type:
	//
	//	*ServiceDetail_General
	//	*ServiceDetail_Couch
	//	*ServiceDetail_Mattress
	//	*ServiceDetail_Car
	//	*ServiceDetail_Post
	Type          isServiceDetail_Type `protobuf_oneof:"type"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceDetail) Reset() {
	*x = ServiceDetail{}
	mi := &file_booking_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceDetail) ProtoMessage() {}

func (x *ServiceDetail) ProtoReflect() protoreflect.Message {
	mi := &file_booking_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceDetail.ProtoReflect.Descriptor instead.
func (*ServiceDetail) Descriptor() ([]byte, []int) {
	return file_booking_proto_rawDescGZIP(), []int{4}
}

func (x *ServiceDetail) GetType() isServiceDetail_Type {
	if x != nil {
		return x.Type
	}
	return nil
}

func (x *ServiceDetail) GetGeneral() *GeneralCleaningDetails {
	if x != nil {
		if x, ok := x.Type.(*ServiceDetail_General); ok {
			return x.General
		}
	}
	return nil
}

func (x *ServiceDetail) GetCouch() *CouchCleaningDetails {
	if x != nil {
		if x, ok := x.Type.(*ServiceDetail_Couch); ok {
			return x.Couch
		}
	}
	return nil
}

func (x *ServiceDetail) GetMattress() *MattressCleaningDetails {
	if x != nil {
		if x, ok := x.Type.(*ServiceDetail_Mattress); ok {
			return x.Mattress
		}
	}
	return nil
}

func (x *ServiceDetail) GetCar() *CarCleaningDetails {
	if x != nil {
		if x, ok := x.Type.(*ServiceDetail_Car); ok {
			return x.Car
		}
	}
	return nil
}

func (x *ServiceDetail) GetPost() *PostConstructionCleaningDetails {
	if x != nil {
		if x, ok := x.Type.(*ServiceDetail_Post); ok {
			return x.Post
		}
	}
	return nil
}

type isServiceDetail_Type interface {
	isServiceDetail_Type()
}

type ServiceDetail_General struct {
	General *GeneralCleaningDetails `protobuf:"bytes,1,opt,name=general,proto3,oneof"`
}

type ServiceDetail_Couch struct {
	Couch *CouchCleaningDetails `protobuf:"bytes,2,opt,name=couch,proto3,oneof"`
}

type ServiceDetail_Mattress struct {
	Mattress *MattressCleaningDetails `protobuf:"bytes,3,opt,name=mattress,proto3,oneof"`
}

type ServiceDetail_Car struct {
	Car *CarCleaningDetails `protobuf:"bytes,4,opt,name=car,proto3,oneof"`
}

type ServiceDetail_Post struct {
	Post *PostConstructionCleaningDetails `protobuf:"bytes,5,opt,name=post,proto3,oneof"`
}

func (*ServiceDetail_General) isServiceDetail_Type() {}

func (*ServiceDetail_Couch) isServiceDetail_Type() {}

func (*ServiceDetail_Mattress) isServiceDetail_Type() {}

func (*ServiceDetail_Car) isServiceDetail_Type() {}

func (*ServiceDetail_Post) isServiceDetail_Type() {}

type Booking struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Base          *BaseBookingDetails    `protobuf:"bytes,2,opt,name=base,proto3" json:"base,omitempty"`
	MainService   *Services              `protobuf:"bytes,3,opt,name=main_service,json=mainService,proto3" json:"main_service,omitempty"`
	Addons        []*AddOn               `protobuf:"bytes,4,rep,name=addons,proto3" json:"addons,omitempty"`
	Equipment     []*CleaningEquipment   `protobuf:"bytes,5,rep,name=equipment,proto3" json:"equipment,omitempty"`
	Resources     []*CleaningResources   `protobuf:"bytes,6,rep,name=resources,proto3" json:"resources,omitempty"`
	Cleaners      []*CleanerAssigned     `protobuf:"bytes,7,rep,name=cleaners,proto3" json:"cleaners,omitempty"`
	TotalPrice    float32                `protobuf:"fixed32,8,opt,name=total_price,json=totalPrice,proto3" json:"total_price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Booking) Reset() {
	*x = Booking{}
	mi := &file_booking_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Booking) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Booking) ProtoMessage() {}

func (x *Booking) ProtoReflect() protoreflect.Message {
	mi := &file_booking_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Booking.ProtoReflect.Descriptor instead.
func (*Booking) Descriptor() ([]byte, []int) {
	return file_booking_proto_rawDescGZIP(), []int{5}
}

func (x *Booking) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Booking) GetBase() *BaseBookingDetails {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *Booking) GetMainService() *Services {
	if x != nil {
		return x.MainService
	}
	return nil
}

func (x *Booking) GetAddons() []*AddOn {
	if x != nil {
		return x.Addons
	}
	return nil
}

func (x *Booking) GetEquipment() []*CleaningEquipment {
	if x != nil {
		return x.Equipment
	}
	return nil
}

func (x *Booking) GetResources() []*CleaningResources {
	if x != nil {
		return x.Resources
	}
	return nil
}

func (x *Booking) GetCleaners() []*CleanerAssigned {
	if x != nil {
		return x.Cleaners
	}
	return nil
}

func (x *Booking) GetTotalPrice() float32 {
	if x != nil {
		return x.TotalPrice
	}
	return 0
}

type AddOn struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ServiceDetail *Services              `protobuf:"bytes,2,opt,name=serviceDetail,proto3" json:"serviceDetail,omitempty"`
	Price         float32                `protobuf:"fixed32,3,opt,name=price,proto3" json:"price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddOn) Reset() {
	*x = AddOn{}
	mi := &file_booking_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddOn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddOn) ProtoMessage() {}

func (x *AddOn) ProtoReflect() protoreflect.Message {
	mi := &file_booking_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddOn.ProtoReflect.Descriptor instead.
func (*AddOn) Descriptor() ([]byte, []int) {
	return file_booking_proto_rawDescGZIP(), []int{6}
}

func (x *AddOn) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AddOn) GetServiceDetail() *Services {
	if x != nil {
		return x.ServiceDetail
	}
	return nil
}

func (x *AddOn) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

type BaseBookingDetails struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CustId            string                 `protobuf:"bytes,2,opt,name=cust_id,json=custId,proto3" json:"cust_id,omitempty"`
	CustomerFirstName string                 `protobuf:"bytes,3,opt,name=customer_first_name,json=customerFirstName,proto3" json:"customer_first_name,omitempty"`
	CustomerLastName  string                 `protobuf:"bytes,4,opt,name=customer_last_name,json=customerLastName,proto3" json:"customer_last_name,omitempty"`
	Address           *Address               `protobuf:"bytes,5,opt,name=address,proto3" json:"address,omitempty"`
	Schedule          *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=schedule,proto3" json:"schedule,omitempty"`
	DirtyScale        int32                  `protobuf:"varint,7,opt,name=dirty_scale,json=dirtyScale,proto3" json:"dirty_scale,omitempty"` // 1 - 5
	PaymentStatus     string                 `protobuf:"bytes,8,opt,name=payment_status,json=paymentStatus,proto3" json:"payment_status,omitempty"`
	ReviewStatus      string                 `protobuf:"bytes,9,opt,name=review_status,json=reviewStatus,proto3" json:"review_status,omitempty"`
	Photos            []string               `protobuf:"bytes,10,rep,name=photos,proto3" json:"photos,omitempty"` // file IDs or URLs
	CreatedAt         *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt         *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *BaseBookingDetails) Reset() {
	*x = BaseBookingDetails{}
	mi := &file_booking_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BaseBookingDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseBookingDetails) ProtoMessage() {}

func (x *BaseBookingDetails) ProtoReflect() protoreflect.Message {
	mi := &file_booking_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseBookingDetails.ProtoReflect.Descriptor instead.
func (*BaseBookingDetails) Descriptor() ([]byte, []int) {
	return file_booking_proto_rawDescGZIP(), []int{7}
}

func (x *BaseBookingDetails) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *BaseBookingDetails) GetCustId() string {
	if x != nil {
		return x.CustId
	}
	return ""
}

func (x *BaseBookingDetails) GetCustomerFirstName() string {
	if x != nil {
		return x.CustomerFirstName
	}
	return ""
}

func (x *BaseBookingDetails) GetCustomerLastName() string {
	if x != nil {
		return x.CustomerLastName
	}
	return ""
}

func (x *BaseBookingDetails) GetAddress() *Address {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *BaseBookingDetails) GetSchedule() *timestamppb.Timestamp {
	if x != nil {
		return x.Schedule
	}
	return nil
}

func (x *BaseBookingDetails) GetDirtyScale() int32 {
	if x != nil {
		return x.DirtyScale
	}
	return 0
}

func (x *BaseBookingDetails) GetPaymentStatus() string {
	if x != nil {
		return x.PaymentStatus
	}
	return ""
}

func (x *BaseBookingDetails) GetReviewStatus() string {
	if x != nil {
		return x.ReviewStatus
	}
	return ""
}

func (x *BaseBookingDetails) GetPhotos() []string {
	if x != nil {
		return x.Photos
	}
	return nil
}

func (x *BaseBookingDetails) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *BaseBookingDetails) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type CreateBookingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *BaseBookingDetails    `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	MainService   *Services              `protobuf:"bytes,2,opt,name=main_service,json=mainService,proto3" json:"main_service,omitempty"`
	Addons        []*AddOn               `protobuf:"bytes,3,rep,name=addons,proto3" json:"addons,omitempty"`
	Equipment     []*CleaningEquipment   `protobuf:"bytes,4,rep,name=equipment,proto3" json:"equipment,omitempty"`
	Resources     []*CleaningResources   `protobuf:"bytes,5,rep,name=resources,proto3" json:"resources,omitempty"`
	Cleaners      []*CleanerAssigned     `protobuf:"bytes,6,rep,name=cleaners,proto3" json:"cleaners,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBookingRequest) Reset() {
	*x = CreateBookingRequest{}
	mi := &file_booking_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBookingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBookingRequest) ProtoMessage() {}

func (x *CreateBookingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_booking_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBookingRequest.ProtoReflect.Descriptor instead.
func (*CreateBookingRequest) Descriptor() ([]byte, []int) {
	return file_booking_proto_rawDescGZIP(), []int{8}
}

func (x *CreateBookingRequest) GetBase() *BaseBookingDetails {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *CreateBookingRequest) GetMainService() *Services {
	if x != nil {
		return x.MainService
	}
	return nil
}

func (x *CreateBookingRequest) GetAddons() []*AddOn {
	if x != nil {
		return x.Addons
	}
	return nil
}

func (x *CreateBookingRequest) GetEquipment() []*CleaningEquipment {
	if x != nil {
		return x.Equipment
	}
	return nil
}

func (x *CreateBookingRequest) GetResources() []*CleaningResources {
	if x != nil {
		return x.Resources
	}
	return nil
}

func (x *CreateBookingRequest) GetCleaners() []*CleanerAssigned {
	if x != nil {
		return x.Cleaners
	}
	return nil
}

type CreateBookingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Book          *Booking               `protobuf:"bytes,1,opt,name=book,proto3" json:"book,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBookingResponse) Reset() {
	*x = CreateBookingResponse{}
	mi := &file_booking_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBookingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBookingResponse) ProtoMessage() {}

func (x *CreateBookingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_booking_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBookingResponse.ProtoReflect.Descriptor instead.
func (*CreateBookingResponse) Descriptor() ([]byte, []int) {
	return file_booking_proto_rawDescGZIP(), []int{9}
}

func (x *CreateBookingResponse) GetBook() *Booking {
	if x != nil {
		return x.Book
	}
	return nil
}

type Services struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ServiceType   MainServiceType        `protobuf:"varint,2,opt,name=service_type,json=serviceType,proto3,enum=MainServiceType" json:"service_type,omitempty"`
	Details       *ServiceDetail         `protobuf:"bytes,3,opt,name=details,proto3" json:"details,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Services) Reset() {
	*x = Services{}
	mi := &file_booking_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Services) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Services) ProtoMessage() {}

func (x *Services) ProtoReflect() protoreflect.Message {
	mi := &file_booking_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Services.ProtoReflect.Descriptor instead.
func (*Services) Descriptor() ([]byte, []int) {
	return file_booking_proto_rawDescGZIP(), []int{10}
}

func (x *Services) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Services) GetServiceType() MainServiceType {
	if x != nil {
		return x.ServiceType
	}
	return MainServiceType_SERVICE_TYPE_UNSPECIFIED
}

func (x *Services) GetDetails() *ServiceDetail {
	if x != nil {
		return x.Details
	}
	return nil
}

// General cleaning
type GeneralCleaningDetails struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HomeType      HomeType               `protobuf:"varint,2,opt,name=home_type,json=homeType,proto3,enum=HomeType" json:"home_type,omitempty"`
	Sqm           int32                  `protobuf:"varint,3,opt,name=sqm,proto3" json:"sqm,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GeneralCleaningDetails) Reset() {
	*x = GeneralCleaningDetails{}
	mi := &file_booking_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GeneralCleaningDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeneralCleaningDetails) ProtoMessage() {}

func (x *GeneralCleaningDetails) ProtoReflect() protoreflect.Message {
	mi := &file_booking_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeneralCleaningDetails.ProtoReflect.Descriptor instead.
func (*GeneralCleaningDetails) Descriptor() ([]byte, []int) {
	return file_booking_proto_rawDescGZIP(), []int{11}
}

func (x *GeneralCleaningDetails) GetHomeType() HomeType {
	if x != nil {
		return x.HomeType
	}
	return HomeType_CONDO_ROOM
}

func (x *GeneralCleaningDetails) GetSqm() int32 {
	if x != nil {
		return x.Sqm
	}
	return 0
}

// Couch cleaning
type CouchCleaningDetails struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CouchType     CouchType              `protobuf:"varint,2,opt,name=couch_type,json=couchType,proto3,enum=CouchType" json:"couch_type,omitempty"`
	WidthCm       int32                  `protobuf:"varint,3,opt,name=width_cm,json=widthCm,proto3" json:"width_cm,omitempty"`
	DepthCm       int32                  `protobuf:"varint,4,opt,name=depth_cm,json=depthCm,proto3" json:"depth_cm,omitempty"`
	HeightCm      int32                  `protobuf:"varint,5,opt,name=height_cm,json=heightCm,proto3" json:"height_cm,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CouchCleaningDetails) Reset() {
	*x = CouchCleaningDetails{}
	mi := &file_booking_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CouchCleaningDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CouchCleaningDetails) ProtoMessage() {}

func (x *CouchCleaningDetails) ProtoReflect() protoreflect.Message {
	mi := &file_booking_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CouchCleaningDetails.ProtoReflect.Descriptor instead.
func (*CouchCleaningDetails) Descriptor() ([]byte, []int) {
	return file_booking_proto_rawDescGZIP(), []int{12}
}

func (x *CouchCleaningDetails) GetCouchType() CouchType {
	if x != nil {
		return x.CouchType
	}
	return CouchType_SEATER_1
}

func (x *CouchCleaningDetails) GetWidthCm() int32 {
	if x != nil {
		return x.WidthCm
	}
	return 0
}

func (x *CouchCleaningDetails) GetDepthCm() int32 {
	if x != nil {
		return x.DepthCm
	}
	return 0
}

func (x *CouchCleaningDetails) GetHeightCm() int32 {
	if x != nil {
		return x.HeightCm
	}
	return 0
}

// Mattress cleaning
type MattressCleaningDetails struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BedType       BedType                `protobuf:"varint,2,opt,name=bed_type,json=bedType,proto3,enum=BedType" json:"bed_type,omitempty"`
	WidthCm       int32                  `protobuf:"varint,3,opt,name=width_cm,json=widthCm,proto3" json:"width_cm,omitempty"`
	DepthCm       int32                  `protobuf:"varint,4,opt,name=depth_cm,json=depthCm,proto3" json:"depth_cm,omitempty"`
	HeightCm      int32                  `protobuf:"varint,5,opt,name=height_cm,json=heightCm,proto3" json:"height_cm,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MattressCleaningDetails) Reset() {
	*x = MattressCleaningDetails{}
	mi := &file_booking_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MattressCleaningDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MattressCleaningDetails) ProtoMessage() {}

func (x *MattressCleaningDetails) ProtoReflect() protoreflect.Message {
	mi := &file_booking_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MattressCleaningDetails.ProtoReflect.Descriptor instead.
func (*MattressCleaningDetails) Descriptor() ([]byte, []int) {
	return file_booking_proto_rawDescGZIP(), []int{13}
}

func (x *MattressCleaningDetails) GetBedType() BedType {
	if x != nil {
		return x.BedType
	}
	return BedType_KING
}

func (x *MattressCleaningDetails) GetWidthCm() int32 {
	if x != nil {
		return x.WidthCm
	}
	return 0
}

func (x *MattressCleaningDetails) GetDepthCm() int32 {
	if x != nil {
		return x.DepthCm
	}
	return 0
}

func (x *MattressCleaningDetails) GetHeightCm() int32 {
	if x != nil {
		return x.HeightCm
	}
	return 0
}

// Car interior cleaning
type CarCleaningDetails struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CarType       CarType                `protobuf:"varint,2,opt,name=car_type,json=carType,proto3,enum=CarType" json:"car_type,omitempty"`
	ChildSeats    int32                  `protobuf:"varint,3,opt,name=child_seats,json=childSeats,proto3" json:"child_seats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CarCleaningDetails) Reset() {
	*x = CarCleaningDetails{}
	mi := &file_booking_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CarCleaningDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CarCleaningDetails) ProtoMessage() {}

func (x *CarCleaningDetails) ProtoReflect() protoreflect.Message {
	mi := &file_booking_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CarCleaningDetails.ProtoReflect.Descriptor instead.
func (*CarCleaningDetails) Descriptor() ([]byte, []int) {
	return file_booking_proto_rawDescGZIP(), []int{14}
}

func (x *CarCleaningDetails) GetCarType() CarType {
	if x != nil {
		return x.CarType
	}
	return CarType_SEDAN
}

func (x *CarCleaningDetails) GetChildSeats() int32 {
	if x != nil {
		return x.ChildSeats
	}
	return 0
}

// Post-construction cleaning
type PostConstructionCleaningDetails struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sqm           int32                  `protobuf:"varint,2,opt,name=sqm,proto3" json:"sqm,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostConstructionCleaningDetails) Reset() {
	*x = PostConstructionCleaningDetails{}
	mi := &file_booking_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostConstructionCleaningDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostConstructionCleaningDetails) ProtoMessage() {}

func (x *PostConstructionCleaningDetails) ProtoReflect() protoreflect.Message {
	mi := &file_booking_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostConstructionCleaningDetails.ProtoReflect.Descriptor instead.
func (*PostConstructionCleaningDetails) Descriptor() ([]byte, []int) {
	return file_booking_proto_rawDescGZIP(), []int{15}
}

func (x *PostConstructionCleaningDetails) GetSqm() int32 {
	if x != nil {
		return x.Sqm
	}
	return 0
}

type QuoteRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Details:
	//
	//	*QuoteRequest_General
	//	*QuoteRequest_Couch
	//	*QuoteRequest_Mattress
	//	*QuoteRequest_Car
	//	*QuoteRequest_Post
	Details       isQuoteRequest_Details `protobuf_oneof:"details"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuoteRequest) Reset() {
	*x = QuoteRequest{}
	mi := &file_booking_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuoteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuoteRequest) ProtoMessage() {}

func (x *QuoteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_booking_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuoteRequest.ProtoReflect.Descriptor instead.
func (*QuoteRequest) Descriptor() ([]byte, []int) {
	return file_booking_proto_rawDescGZIP(), []int{16}
}

func (x *QuoteRequest) GetDetails() isQuoteRequest_Details {
	if x != nil {
		return x.Details
	}
	return nil
}

func (x *QuoteRequest) GetGeneral() *GeneralCleaningDetails {
	if x != nil {
		if x, ok := x.Details.(*QuoteRequest_General); ok {
			return x.General
		}
	}
	return nil
}

func (x *QuoteRequest) GetCouch() *CouchCleaningDetails {
	if x != nil {
		if x, ok := x.Details.(*QuoteRequest_Couch); ok {
			return x.Couch
		}
	}
	return nil
}

func (x *QuoteRequest) GetMattress() *MattressCleaningDetails {
	if x != nil {
		if x, ok := x.Details.(*QuoteRequest_Mattress); ok {
			return x.Mattress
		}
	}
	return nil
}

func (x *QuoteRequest) GetCar() *CarCleaningDetails {
	if x != nil {
		if x, ok := x.Details.(*QuoteRequest_Car); ok {
			return x.Car
		}
	}
	return nil
}

func (x *QuoteRequest) GetPost() *PostConstructionCleaningDetails {
	if x != nil {
		if x, ok := x.Details.(*QuoteRequest_Post); ok {
			return x.Post
		}
	}
	return nil
}

type isQuoteRequest_Details interface {
	isQuoteRequest_Details()
}

type QuoteRequest_General struct {
	General *GeneralCleaningDetails `protobuf:"bytes,1,opt,name=general,proto3,oneof"`
}

type QuoteRequest_Couch struct {
	Couch *CouchCleaningDetails `protobuf:"bytes,2,opt,name=couch,proto3,oneof"`
}

type QuoteRequest_Mattress struct {
	Mattress *MattressCleaningDetails `protobuf:"bytes,3,opt,name=mattress,proto3,oneof"`
}

type QuoteRequest_Car struct {
	Car *CarCleaningDetails `protobuf:"bytes,4,opt,name=car,proto3,oneof"`
}

type QuoteRequest_Post struct {
	Post *PostConstructionCleaningDetails `protobuf:"bytes,5,opt,name=post,proto3,oneof"`
}

func (*QuoteRequest_General) isQuoteRequest_Details() {}

func (*QuoteRequest_Couch) isQuoteRequest_Details() {}

func (*QuoteRequest_Mattress) isQuoteRequest_Details() {}

func (*QuoteRequest_Car) isQuoteRequest_Details() {}

func (*QuoteRequest_Post) isQuoteRequest_Details() {}

type QuoteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TotalPrice    float32                `protobuf:"fixed32,1,opt,name=total_price,json=totalPrice,proto3" json:"total_price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuoteResponse) Reset() {
	*x = QuoteResponse{}
	mi := &file_booking_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuoteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuoteResponse) ProtoMessage() {}

func (x *QuoteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_booking_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuoteResponse.ProtoReflect.Descriptor instead.
func (*QuoteResponse) Descriptor() ([]byte, []int) {
	return file_booking_proto_rawDescGZIP(), []int{17}
}

func (x *QuoteResponse) GetTotalPrice() float32 {
	if x != nil {
		return x.TotalPrice
	}
	return 0
}

type CalculateQuotePriceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Quote         *QuoteRequest          `protobuf:"bytes,1,opt,name=quote,proto3" json:"quote,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CalculateQuotePriceRequest) Reset() {
	*x = CalculateQuotePriceRequest{}
	mi := &file_booking_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalculateQuotePriceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculateQuotePriceRequest) ProtoMessage() {}

func (x *CalculateQuotePriceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_booking_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculateQuotePriceRequest.ProtoReflect.Descriptor instead.
func (*CalculateQuotePriceRequest) Descriptor() ([]byte, []int) {
	return file_booking_proto_rawDescGZIP(), []int{18}
}

func (x *CalculateQuotePriceRequest) GetQuote() *QuoteRequest {
	if x != nil {
		return x.Quote
	}
	return nil
}

type CalculateQuotePriceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TotalPrice    float32                `protobuf:"fixed32,1,opt,name=total_price,json=totalPrice,proto3" json:"total_price,omitempty"`
	Breakdown     []*PricingBreakdown    `protobuf:"bytes,2,rep,name=breakdown,proto3" json:"breakdown,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CalculateQuotePriceResponse) Reset() {
	*x = CalculateQuotePriceResponse{}
	mi := &file_booking_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalculateQuotePriceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculateQuotePriceResponse) ProtoMessage() {}

func (x *CalculateQuotePriceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_booking_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculateQuotePriceResponse.ProtoReflect.Descriptor instead.
func (*CalculateQuotePriceResponse) Descriptor() ([]byte, []int) {
	return file_booking_proto_rawDescGZIP(), []int{19}
}

func (x *CalculateQuotePriceResponse) GetTotalPrice() float32 {
	if x != nil {
		return x.TotalPrice
	}
	return 0
}

func (x *CalculateQuotePriceResponse) GetBreakdown() []*PricingBreakdown {
	if x != nil {
		return x.Breakdown
	}
	return nil
}

type CalculatePriceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Booking       *CreateBookingRequest  `protobuf:"bytes,1,opt,name=booking,proto3" json:"booking,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CalculatePriceRequest) Reset() {
	*x = CalculatePriceRequest{}
	mi := &file_booking_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalculatePriceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculatePriceRequest) ProtoMessage() {}

func (x *CalculatePriceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_booking_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculatePriceRequest.ProtoReflect.Descriptor instead.
func (*CalculatePriceRequest) Descriptor() ([]byte, []int) {
	return file_booking_proto_rawDescGZIP(), []int{20}
}

func (x *CalculatePriceRequest) GetBooking() *CreateBookingRequest {
	if x != nil {
		return x.Booking
	}
	return nil
}

type CalculatePriceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BasePrice     float32                `protobuf:"fixed32,1,opt,name=base_price,json=basePrice,proto3" json:"base_price,omitempty"`
	Adjustments   float32                `protobuf:"fixed32,2,opt,name=adjustments,proto3" json:"adjustments,omitempty"`
	AddonsPrice   float32                `protobuf:"fixed32,3,opt,name=addons_price,json=addonsPrice,proto3" json:"addons_price,omitempty"`
	TotalPrice    float32                `protobuf:"fixed32,4,opt,name=total_price,json=totalPrice,proto3" json:"total_price,omitempty"`
	Breakdown     []*PricingBreakdown    `protobuf:"bytes,5,rep,name=breakdown,proto3" json:"breakdown,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CalculatePriceResponse) Reset() {
	*x = CalculatePriceResponse{}
	mi := &file_booking_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalculatePriceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculatePriceResponse) ProtoMessage() {}

func (x *CalculatePriceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_booking_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculatePriceResponse.ProtoReflect.Descriptor instead.
func (*CalculatePriceResponse) Descriptor() ([]byte, []int) {
	return file_booking_proto_rawDescGZIP(), []int{21}
}

func (x *CalculatePriceResponse) GetBasePrice() float32 {
	if x != nil {
		return x.BasePrice
	}
	return 0
}

func (x *CalculatePriceResponse) GetAdjustments() float32 {
	if x != nil {
		return x.Adjustments
	}
	return 0
}

func (x *CalculatePriceResponse) GetAddonsPrice() float32 {
	if x != nil {
		return x.AddonsPrice
	}
	return 0
}

func (x *CalculatePriceResponse) GetTotalPrice() float32 {
	if x != nil {
		return x.TotalPrice
	}
	return 0
}

func (x *CalculatePriceResponse) GetBreakdown() []*PricingBreakdown {
	if x != nil {
		return x.Breakdown
	}
	return nil
}

type PricingBreakdown struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Description   string                 `protobuf:"bytes,1,opt,name=description,proto3" json:"description,omitempty"`
	Amount        float32                `protobuf:"fixed32,2,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PricingBreakdown) Reset() {
	*x = PricingBreakdown{}
	mi := &file_booking_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PricingBreakdown) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PricingBreakdown) ProtoMessage() {}

func (x *PricingBreakdown) ProtoReflect() protoreflect.Message {
	mi := &file_booking_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PricingBreakdown.ProtoReflect.Descriptor instead.
func (*PricingBreakdown) Descriptor() ([]byte, []int) {
	return file_booking_proto_rawDescGZIP(), []int{22}
}

func (x *PricingBreakdown) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *PricingBreakdown) GetAmount() float32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type GetBookingByIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BookingId     string                 `protobuf:"bytes,1,opt,name=booking_id,json=bookingId,proto3" json:"booking_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBookingByIdRequest) Reset() {
	*x = GetBookingByIdRequest{}
	mi := &file_booking_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBookingByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBookingByIdRequest) ProtoMessage() {}

func (x *GetBookingByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_booking_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBookingByIdRequest.ProtoReflect.Descriptor instead.
func (*GetBookingByIdRequest) Descriptor() ([]byte, []int) {
	return file_booking_proto_rawDescGZIP(), []int{23}
}

func (x *GetBookingByIdRequest) GetBookingId() string {
	if x != nil {
		return x.BookingId
	}
	return ""
}

type GetBookingByIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Booking       *Booking               `protobuf:"bytes,1,opt,name=booking,proto3" json:"booking,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBookingByIdResponse) Reset() {
	*x = GetBookingByIdResponse{}
	mi := &file_booking_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBookingByIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBookingByIdResponse) ProtoMessage() {}

func (x *GetBookingByIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_booking_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBookingByIdResponse.ProtoReflect.Descriptor instead.
func (*GetBookingByIdResponse) Descriptor() ([]byte, []int) {
	return file_booking_proto_rawDescGZIP(), []int{24}
}

func (x *GetBookingByIdResponse) GetBooking() *Booking {
	if x != nil {
		return x.Booking
	}
	return nil
}

type GetBookingByUIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBookingByUIdRequest) Reset() {
	*x = GetBookingByUIdRequest{}
	mi := &file_booking_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBookingByUIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBookingByUIdRequest) ProtoMessage() {}

func (x *GetBookingByUIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_booking_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBookingByUIdRequest.ProtoReflect.Descriptor instead.
func (*GetBookingByUIdRequest) Descriptor() ([]byte, []int) {
	return file_booking_proto_rawDescGZIP(), []int{25}
}

func (x *GetBookingByUIdRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetBookingByUIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Booking       []*Booking             `protobuf:"bytes,1,rep,name=Booking,proto3" json:"Booking,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBookingByUIdResponse) Reset() {
	*x = GetBookingByUIdResponse{}
	mi := &file_booking_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBookingByUIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBookingByUIdResponse) ProtoMessage() {}

func (x *GetBookingByUIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_booking_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBookingByUIdResponse.ProtoReflect.Descriptor instead.
func (*GetBookingByUIdResponse) Descriptor() ([]byte, []int) {
	return file_booking_proto_rawDescGZIP(), []int{26}
}

func (x *GetBookingByUIdResponse) GetBooking() []*Booking {
	if x != nil {
		return x.Booking
	}
	return nil
}

type DeleteBookingByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BookingId     string                 `protobuf:"bytes,1,opt,name=booking_id,json=bookingId,proto3" json:"booking_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteBookingByIDRequest) Reset() {
	*x = DeleteBookingByIDRequest{}
	mi := &file_booking_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteBookingByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBookingByIDRequest) ProtoMessage() {}

func (x *DeleteBookingByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_booking_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBookingByIDRequest.ProtoReflect.Descriptor instead.
func (*DeleteBookingByIDRequest) Descriptor() ([]byte, []int) {
	return file_booking_proto_rawDescGZIP(), []int{27}
}

func (x *DeleteBookingByIDRequest) GetBookingId() string {
	if x != nil {
		return x.BookingId
	}
	return ""
}

type DeleteBookingByIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteBookingByIDResponse) Reset() {
	*x = DeleteBookingByIDResponse{}
	mi := &file_booking_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteBookingByIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBookingByIDResponse) ProtoMessage() {}

func (x *DeleteBookingByIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_booking_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBookingByIDResponse.ProtoReflect.Descriptor instead.
func (*DeleteBookingByIDResponse) Descriptor() ([]byte, []int) {
	return file_booking_proto_rawDescGZIP(), []int{28}
}

func (x *DeleteBookingByIDResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type DeleteBookingAddonByIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AddonId       string                 `protobuf:"bytes,1,opt,name=addon_id,json=addonId,proto3" json:"addon_id,omitempty"`
	BookingId     string                 `protobuf:"bytes,2,opt,name=booking_id,json=bookingId,proto3" json:"booking_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteBookingAddonByIdRequest) Reset() {
	*x = DeleteBookingAddonByIdRequest{}
	mi := &file_booking_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteBookingAddonByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBookingAddonByIdRequest) ProtoMessage() {}

func (x *DeleteBookingAddonByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_booking_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBookingAddonByIdRequest.ProtoReflect.Descriptor instead.
func (*DeleteBookingAddonByIdRequest) Descriptor() ([]byte, []int) {
	return file_booking_proto_rawDescGZIP(), []int{29}
}

func (x *DeleteBookingAddonByIdRequest) GetAddonId() string {
	if x != nil {
		return x.AddonId
	}
	return ""
}

func (x *DeleteBookingAddonByIdRequest) GetBookingId() string {
	if x != nil {
		return x.BookingId
	}
	return ""
}

type DeleteBookingAddonByIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteBookingAddonByIdResponse) Reset() {
	*x = DeleteBookingAddonByIdResponse{}
	mi := &file_booking_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteBookingAddonByIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBookingAddonByIdResponse) ProtoMessage() {}

func (x *DeleteBookingAddonByIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_booking_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBookingAddonByIdResponse.ProtoReflect.Descriptor instead.
func (*DeleteBookingAddonByIdResponse) Descriptor() ([]byte, []int) {
	return file_booking_proto_rawDescGZIP(), []int{30}
}

func (x *DeleteBookingAddonByIdResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_booking_proto protoreflect.FileDescriptor

const file_booking_proto_rawDesc = "" +
	"\n" +
	"\rbooking.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"p\n" +
	"\aAddress\x12#\n" +
	"\raddress_human\x18\x01 \x01(\tR\faddressHuman\x12\x1f\n" +
	"\vaddress_lat\x18\x02 \x01(\x01R\n" +
	"addressLat\x12\x1f\n" +
	"\vaddress_lng\x18\x03 \x01(\x01R\n" +
	"addressLng\"h\n" +
	"\x11CleaningEquipment\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x1b\n" +
	"\tphoto_url\x18\x04 \x01(\tR\bphotoUrl\"h\n" +
	"\x11CleaningResources\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x1b\n" +
	"\tphoto_url\x18\x04 \x01(\tR\bphotoUrl\"\x94\x01\n" +
	"\x0fCleanerAssigned\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12,\n" +
	"\x12cleaner_first_name\x18\x02 \x01(\tR\x10cleanerFirstName\x12*\n" +
	"\x11cleaner_last_name\x18\x03 \x01(\tR\x0fcleanerLastName\x12\x17\n" +
	"\apfp_url\x18\x04 \x01(\tR\x06pfpUrl\"\x94\x02\n" +
	"\rServiceDetail\x123\n" +
	"\ageneral\x18\x01 \x01(\v2\x17.GeneralCleaningDetailsH\x00R\ageneral\x12-\n" +
	"\x05couch\x18\x02 \x01(\v2\x15.CouchCleaningDetailsH\x00R\x05couch\x126\n" +
	"\bmattress\x18\x03 \x01(\v2\x18.MattressCleaningDetailsH\x00R\bmattress\x12'\n" +
	"\x03car\x18\x04 \x01(\v2\x13.CarCleaningDetailsH\x00R\x03car\x126\n" +
	"\x04post\x18\x05 \x01(\v2 .PostConstructionCleaningDetailsH\x00R\x04postB\x06\n" +
	"\x04type\"\xc3\x02\n" +
	"\aBooking\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12'\n" +
	"\x04base\x18\x02 \x01(\v2\x13.BaseBookingDetailsR\x04base\x12,\n" +
	"\fmain_service\x18\x03 \x01(\v2\t.ServicesR\vmainService\x12\x1e\n" +
	"\x06addons\x18\x04 \x03(\v2\x06.AddOnR\x06addons\x120\n" +
	"\tequipment\x18\x05 \x03(\v2\x12.CleaningEquipmentR\tequipment\x120\n" +
	"\tresources\x18\x06 \x03(\v2\x12.CleaningResourcesR\tresources\x12,\n" +
	"\bcleaners\x18\a \x03(\v2\x10.CleanerAssignedR\bcleaners\x12\x1f\n" +
	"\vtotal_price\x18\b \x01(\x02R\n" +
	"totalPrice\"^\n" +
	"\x05AddOn\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12/\n" +
	"\rserviceDetail\x18\x02 \x01(\v2\t.ServicesR\rserviceDetail\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x02R\x05price\"\xf2\x03\n" +
	"\x12BaseBookingDetails\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\acust_id\x18\x02 \x01(\tR\x06custId\x12.\n" +
	"\x13customer_first_name\x18\x03 \x01(\tR\x11customerFirstName\x12,\n" +
	"\x12customer_last_name\x18\x04 \x01(\tR\x10customerLastName\x12\"\n" +
	"\aaddress\x18\x05 \x01(\v2\b.AddressR\aaddress\x126\n" +
	"\bschedule\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\bschedule\x12\x1f\n" +
	"\vdirty_scale\x18\a \x01(\x05R\n" +
	"dirtyScale\x12%\n" +
	"\x0epayment_status\x18\b \x01(\tR\rpaymentStatus\x12#\n" +
	"\rreview_status\x18\t \x01(\tR\freviewStatus\x12\x16\n" +
	"\x06photos\x18\n" +
	" \x03(\tR\x06photos\x129\n" +
	"\n" +
	"created_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\x9f\x02\n" +
	"\x14CreateBookingRequest\x12'\n" +
	"\x04base\x18\x01 \x01(\v2\x13.BaseBookingDetailsR\x04base\x12,\n" +
	"\fmain_service\x18\x02 \x01(\v2\t.ServicesR\vmainService\x12\x1e\n" +
	"\x06addons\x18\x03 \x03(\v2\x06.AddOnR\x06addons\x120\n" +
	"\tequipment\x18\x04 \x03(\v2\x12.CleaningEquipmentR\tequipment\x120\n" +
	"\tresources\x18\x05 \x03(\v2\x12.CleaningResourcesR\tresources\x12,\n" +
	"\bcleaners\x18\x06 \x03(\v2\x10.CleanerAssignedR\bcleaners\"5\n" +
	"\x15CreateBookingResponse\x12\x1c\n" +
	"\x04book\x18\x01 \x01(\v2\b.BookingR\x04book\"y\n" +
	"\bServices\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x123\n" +
	"\fservice_type\x18\x02 \x01(\x0e2\x10.MainServiceTypeR\vserviceType\x12(\n" +
	"\adetails\x18\x03 \x01(\v2\x0e.ServiceDetailR\adetails\"R\n" +
	"\x16GeneralCleaningDetails\x12&\n" +
	"\thome_type\x18\x02 \x01(\x0e2\t.HomeTypeR\bhomeType\x12\x10\n" +
	"\x03sqm\x18\x03 \x01(\x05R\x03sqm\"\x94\x01\n" +
	"\x14CouchCleaningDetails\x12)\n" +
	"\n" +
	"couch_type\x18\x02 \x01(\x0e2\n" +
	".CouchTypeR\tcouchType\x12\x19\n" +
	"\bwidth_cm\x18\x03 \x01(\x05R\awidthCm\x12\x19\n" +
	"\bdepth_cm\x18\x04 \x01(\x05R\adepthCm\x12\x1b\n" +
	"\theight_cm\x18\x05 \x01(\x05R\bheightCm\"\x91\x01\n" +
	"\x17MattressCleaningDetails\x12#\n" +
	"\bbed_type\x18\x02 \x01(\x0e2\b.BedTypeR\abedType\x12\x19\n" +
	"\bwidth_cm\x18\x03 \x01(\x05R\awidthCm\x12\x19\n" +
	"\bdepth_cm\x18\x04 \x01(\x05R\adepthCm\x12\x1b\n" +
	"\theight_cm\x18\x05 \x01(\x05R\bheightCm\"Z\n" +
	"\x12CarCleaningDetails\x12#\n" +
	"\bcar_type\x18\x02 \x01(\x0e2\b.CarTypeR\acarType\x12\x1f\n" +
	"\vchild_seats\x18\x03 \x01(\x05R\n" +
	"childSeats\"3\n" +
	"\x1fPostConstructionCleaningDetails\x12\x10\n" +
	"\x03sqm\x18\x02 \x01(\x05R\x03sqm\"\x96\x02\n" +
	"\fQuoteRequest\x123\n" +
	"\ageneral\x18\x01 \x01(\v2\x17.GeneralCleaningDetailsH\x00R\ageneral\x12-\n" +
	"\x05couch\x18\x02 \x01(\v2\x15.CouchCleaningDetailsH\x00R\x05couch\x126\n" +
	"\bmattress\x18\x03 \x01(\v2\x18.MattressCleaningDetailsH\x00R\bmattress\x12'\n" +
	"\x03car\x18\x04 \x01(\v2\x13.CarCleaningDetailsH\x00R\x03car\x126\n" +
	"\x04post\x18\x05 \x01(\v2 .PostConstructionCleaningDetailsH\x00R\x04postB\t\n" +
	"\adetails\"0\n" +
	"\rQuoteResponse\x12\x1f\n" +
	"\vtotal_price\x18\x01 \x01(\x02R\n" +
	"totalPrice\"A\n" +
	"\x1aCalculateQuotePriceRequest\x12#\n" +
	"\x05quote\x18\x01 \x01(\v2\r.QuoteRequestR\x05quote\"o\n" +
	"\x1bCalculateQuotePriceResponse\x12\x1f\n" +
	"\vtotal_price\x18\x01 \x01(\x02R\n" +
	"totalPrice\x12/\n" +
	"\tbreakdown\x18\x02 \x03(\v2\x11.PricingBreakdownR\tbreakdown\"H\n" +
	"\x15CalculatePriceRequest\x12/\n" +
	"\abooking\x18\x01 \x01(\v2\x15.CreateBookingRequestR\abooking\"\xce\x01\n" +
	"\x16CalculatePriceResponse\x12\x1d\n" +
	"\n" +
	"base_price\x18\x01 \x01(\x02R\tbasePrice\x12 \n" +
	"\vadjustments\x18\x02 \x01(\x02R\vadjustments\x12!\n" +
	"\faddons_price\x18\x03 \x01(\x02R\vaddonsPrice\x12\x1f\n" +
	"\vtotal_price\x18\x04 \x01(\x02R\n" +
	"totalPrice\x12/\n" +
	"\tbreakdown\x18\x05 \x03(\v2\x11.PricingBreakdownR\tbreakdown\"L\n" +
	"\x10PricingBreakdown\x12 \n" +
	"\vdescription\x18\x01 \x01(\tR\vdescription\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x02R\x06amount\"6\n" +
	"\x15GetBookingByIdRequest\x12\x1d\n" +
	"\n" +
	"booking_id\x18\x01 \x01(\tR\tbookingId\"<\n" +
	"\x16GetBookingByIdResponse\x12\"\n" +
	"\abooking\x18\x01 \x01(\v2\b.BookingR\abooking\"1\n" +
	"\x16GetBookingByUIdRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"=\n" +
	"\x17GetBookingByUIdResponse\x12\"\n" +
	"\aBooking\x18\x01 \x03(\v2\b.BookingR\aBooking\"9\n" +
	"\x18DeleteBookingByIDRequest\x12\x1d\n" +
	"\n" +
	"booking_id\x18\x01 \x01(\tR\tbookingId\"5\n" +
	"\x19DeleteBookingByIDResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"Y\n" +
	"\x1dDeleteBookingAddonByIdRequest\x12\x19\n" +
	"\baddon_id\x18\x01 \x01(\tR\aaddonId\x12\x1d\n" +
	"\n" +
	"booking_id\x18\x02 \x01(\tR\tbookingId\":\n" +
	"\x1eDeleteBookingAddonByIdResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess*h\n" +
	"\x0fMainServiceType\x12\x1c\n" +
	"\x18SERVICE_TYPE_UNSPECIFIED\x10\x00\x12\v\n" +
	"\aGENERAL\x10\x01\x12\t\n" +
	"\x05COUCH\x10\x02\x12\f\n" +
	"\bMATTRESS\x10\x03\x12\a\n" +
	"\x03CAR\x10\x04\x12\b\n" +
	"\x04POST\x10\x05*5\n" +
	"\bHomeType\x12\x0e\n" +
	"\n" +
	"CONDO_ROOM\x10\x00\x12\t\n" +
	"\x05HOUSE\x10\x01\x12\x0e\n" +
	"\n" +
	"COMMERCIAL\x10\x02*\xe9\x01\n" +
	"\tCouchType\x12\f\n" +
	"\bSEATER_1\x10\x00\x12\f\n" +
	"\bSEATER_2\x10\x01\x12\f\n" +
	"\bSEATER_3\x10\x02\x12\x18\n" +
	"\x14SEATER_3_LTYPE_SMALL\x10\x03\x12\x18\n" +
	"\x14SEATER_3_LTYPE_LARGE\x10\x04\x12\x18\n" +
	"\x14SEATER_4_LTYPE_SMALL\x10\x05\x12\x18\n" +
	"\x14SEATER_4_LTYPE_LARGE\x10\x06\x12\x12\n" +
	"\x0eSEATER_5_LTYPE\x10\a\x12\x12\n" +
	"\x0eSEATER_6_LTYPE\x10\b\x12\v\n" +
	"\aOTTOMAN\x10\t\x12\n" +
	"\n" +
	"\x06LAZBOY\x10\n" +
	"\x12\t\n" +
	"\x05CHAIR\x10\v*m\n" +
	"\aBedType\x12\b\n" +
	"\x04KING\x10\x00\x12\t\n" +
	"\x05QUEEN\x10\x01\x12\x11\n" +
	"\rKING_HEADBAND\x10\x02\x12\x12\n" +
	"\x0eQUEEN_HEADBAND\x10\x03\x12\n" +
	"\n" +
	"\x06DOUBLE\x10\x04\x12\n" +
	"\n" +
	"\x06SINGLE\x10\x05\x12\x0e\n" +
	"\n" +
	"BED_PILLOW\x10\x06*J\n" +
	"\aCarType\x12\t\n" +
	"\x05SEDAN\x10\x00\x12\a\n" +
	"\x03MPV\x10\x01\x12\a\n" +
	"\x03SUV\x10\x02\x12\n" +
	"\n" +
	"\x06PICKUP\x10\x03\x12\a\n" +
	"\x03VAN\x10\x04\x12\r\n" +
	"\tCAR_SMALL\x10\x052\xe4\x03\n" +
	"\x0eBookingService\x12>\n" +
	"\rCreateBooking\x12\x15.CreateBookingRequest\x1a\x16.CreateBookingResponse\x12A\n" +
	"\x0eCalculatePrice\x12\x16.CalculatePriceRequest\x1a\x17.CalculatePriceResponse\x12A\n" +
	"\x0eGetBookingById\x12\x16.GetBookingByIdRequest\x1a\x17.GetBookingByIdResponse\x12D\n" +
	"\x0fGetBookingByUId\x12\x17.GetBookingByUIdRequest\x1a\x18.GetBookingByUIdResponse\x12#\n" +
	"\rUpdateBooking\x12\b.Booking\x1a\b.Booking\x12F\n" +
	"\rDeleteBooking\x12\x19.DeleteBookingByIDRequest\x1a\x1a.DeleteBookingByIDResponse\x12Y\n" +
	"\x16DeleteBookingAddonById\x12\x1e.DeleteBookingAddonByIdRequest\x1a\x1f.DeleteBookingAddonByIdResponseB\x1fZ\x1dhandworks/common/grpc/bookingb\x06proto3"

var (
	file_booking_proto_rawDescOnce sync.Once
	file_booking_proto_rawDescData []byte
)

func file_booking_proto_rawDescGZIP() []byte {
	file_booking_proto_rawDescOnce.Do(func() {
		file_booking_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_booking_proto_rawDesc), len(file_booking_proto_rawDesc)))
	})
	return file_booking_proto_rawDescData
}

var file_booking_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_booking_proto_msgTypes = make([]protoimpl.MessageInfo, 31)
var file_booking_proto_goTypes = []any{
	(MainServiceType)(0),                    // 0: MainServiceType
	(HomeType)(0),                           // 1: HomeType
	(CouchType)(0),                          // 2: CouchType
	(BedType)(0),                            // 3: BedType
	(CarType)(0),                            // 4: CarType
	(*Address)(nil),                         // 5: Address
	(*CleaningEquipment)(nil),               // 6: CleaningEquipment
	(*CleaningResources)(nil),               // 7: CleaningResources
	(*CleanerAssigned)(nil),                 // 8: CleanerAssigned
	(*ServiceDetail)(nil),                   // 9: ServiceDetail
	(*Booking)(nil),                         // 10: Booking
	(*AddOn)(nil),                           // 11: AddOn
	(*BaseBookingDetails)(nil),              // 12: BaseBookingDetails
	(*CreateBookingRequest)(nil),            // 13: CreateBookingRequest
	(*CreateBookingResponse)(nil),           // 14: CreateBookingResponse
	(*Services)(nil),                        // 15: Services
	(*GeneralCleaningDetails)(nil),          // 16: GeneralCleaningDetails
	(*CouchCleaningDetails)(nil),            // 17: CouchCleaningDetails
	(*MattressCleaningDetails)(nil),         // 18: MattressCleaningDetails
	(*CarCleaningDetails)(nil),              // 19: CarCleaningDetails
	(*PostConstructionCleaningDetails)(nil), // 20: PostConstructionCleaningDetails
	(*QuoteRequest)(nil),                    // 21: QuoteRequest
	(*QuoteResponse)(nil),                   // 22: QuoteResponse
	(*CalculateQuotePriceRequest)(nil),      // 23: CalculateQuotePriceRequest
	(*CalculateQuotePriceResponse)(nil),     // 24: CalculateQuotePriceResponse
	(*CalculatePriceRequest)(nil),           // 25: CalculatePriceRequest
	(*CalculatePriceResponse)(nil),          // 26: CalculatePriceResponse
	(*PricingBreakdown)(nil),                // 27: PricingBreakdown
	(*GetBookingByIdRequest)(nil),           // 28: GetBookingByIdRequest
	(*GetBookingByIdResponse)(nil),          // 29: GetBookingByIdResponse
	(*GetBookingByUIdRequest)(nil),          // 30: GetBookingByUIdRequest
	(*GetBookingByUIdResponse)(nil),         // 31: GetBookingByUIdResponse
	(*DeleteBookingByIDRequest)(nil),        // 32: DeleteBookingByIDRequest
	(*DeleteBookingByIDResponse)(nil),       // 33: DeleteBookingByIDResponse
	(*DeleteBookingAddonByIdRequest)(nil),   // 34: DeleteBookingAddonByIdRequest
	(*DeleteBookingAddonByIdResponse)(nil),  // 35: DeleteBookingAddonByIdResponse
	(*timestamppb.Timestamp)(nil),           // 36: google.protobuf.Timestamp
}
var file_booking_proto_depIdxs = []int32{
	16, // 0: ServiceDetail.general:type_name -> GeneralCleaningDetails
	17, // 1: ServiceDetail.couch:type_name -> CouchCleaningDetails
	18, // 2: ServiceDetail.mattress:type_name -> MattressCleaningDetails
	19, // 3: ServiceDetail.car:type_name -> CarCleaningDetails
	20, // 4: ServiceDetail.post:type_name -> PostConstructionCleaningDetails
	12, // 5: Booking.base:type_name -> BaseBookingDetails
	15, // 6: Booking.main_service:type_name -> Services
	11, // 7: Booking.addons:type_name -> AddOn
	6,  // 8: Booking.equipment:type_name -> CleaningEquipment
	7,  // 9: Booking.resources:type_name -> CleaningResources
	8,  // 10: Booking.cleaners:type_name -> CleanerAssigned
	15, // 11: AddOn.serviceDetail:type_name -> Services
	5,  // 12: BaseBookingDetails.address:type_name -> Address
	36, // 13: BaseBookingDetails.schedule:type_name -> google.protobuf.Timestamp
	36, // 14: BaseBookingDetails.created_at:type_name -> google.protobuf.Timestamp
	36, // 15: BaseBookingDetails.updated_at:type_name -> google.protobuf.Timestamp
	12, // 16: CreateBookingRequest.base:type_name -> BaseBookingDetails
	15, // 17: CreateBookingRequest.main_service:type_name -> Services
	11, // 18: CreateBookingRequest.addons:type_name -> AddOn
	6,  // 19: CreateBookingRequest.equipment:type_name -> CleaningEquipment
	7,  // 20: CreateBookingRequest.resources:type_name -> CleaningResources
	8,  // 21: CreateBookingRequest.cleaners:type_name -> CleanerAssigned
	10, // 22: CreateBookingResponse.book:type_name -> Booking
	0,  // 23: Services.service_type:type_name -> MainServiceType
	9,  // 24: Services.details:type_name -> ServiceDetail
	1,  // 25: GeneralCleaningDetails.home_type:type_name -> HomeType
	2,  // 26: CouchCleaningDetails.couch_type:type_name -> CouchType
	3,  // 27: MattressCleaningDetails.bed_type:type_name -> BedType
	4,  // 28: CarCleaningDetails.car_type:type_name -> CarType
	16, // 29: QuoteRequest.general:type_name -> GeneralCleaningDetails
	17, // 30: QuoteRequest.couch:type_name -> CouchCleaningDetails
	18, // 31: QuoteRequest.mattress:type_name -> MattressCleaningDetails
	19, // 32: QuoteRequest.car:type_name -> CarCleaningDetails
	20, // 33: QuoteRequest.post:type_name -> PostConstructionCleaningDetails
	21, // 34: CalculateQuotePriceRequest.quote:type_name -> QuoteRequest
	27, // 35: CalculateQuotePriceResponse.breakdown:type_name -> PricingBreakdown
	13, // 36: CalculatePriceRequest.booking:type_name -> CreateBookingRequest
	27, // 37: CalculatePriceResponse.breakdown:type_name -> PricingBreakdown
	10, // 38: GetBookingByIdResponse.booking:type_name -> Booking
	10, // 39: GetBookingByUIdResponse.Booking:type_name -> Booking
	13, // 40: BookingService.CreateBooking:input_type -> CreateBookingRequest
	25, // 41: BookingService.CalculatePrice:input_type -> CalculatePriceRequest
	28, // 42: BookingService.GetBookingById:input_type -> GetBookingByIdRequest
	30, // 43: BookingService.GetBookingByUId:input_type -> GetBookingByUIdRequest
	10, // 44: BookingService.UpdateBooking:input_type -> Booking
	32, // 45: BookingService.DeleteBooking:input_type -> DeleteBookingByIDRequest
	34, // 46: BookingService.DeleteBookingAddonById:input_type -> DeleteBookingAddonByIdRequest
	14, // 47: BookingService.CreateBooking:output_type -> CreateBookingResponse
	26, // 48: BookingService.CalculatePrice:output_type -> CalculatePriceResponse
	29, // 49: BookingService.GetBookingById:output_type -> GetBookingByIdResponse
	31, // 50: BookingService.GetBookingByUId:output_type -> GetBookingByUIdResponse
	10, // 51: BookingService.UpdateBooking:output_type -> Booking
	33, // 52: BookingService.DeleteBooking:output_type -> DeleteBookingByIDResponse
	35, // 53: BookingService.DeleteBookingAddonById:output_type -> DeleteBookingAddonByIdResponse
	47, // [47:54] is the sub-list for method output_type
	40, // [40:47] is the sub-list for method input_type
	40, // [40:40] is the sub-list for extension type_name
	40, // [40:40] is the sub-list for extension extendee
	0,  // [0:40] is the sub-list for field type_name
}

func init() { file_booking_proto_init() }
func file_booking_proto_init() {
	if File_booking_proto != nil {
		return
	}
	file_booking_proto_msgTypes[4].OneofWrappers = []any{
		(*ServiceDetail_General)(nil),
		(*ServiceDetail_Couch)(nil),
		(*ServiceDetail_Mattress)(nil),
		(*ServiceDetail_Car)(nil),
		(*ServiceDetail_Post)(nil),
	}
	file_booking_proto_msgTypes[16].OneofWrappers = []any{
		(*QuoteRequest_General)(nil),
		(*QuoteRequest_Couch)(nil),
		(*QuoteRequest_Mattress)(nil),
		(*QuoteRequest_Car)(nil),
		(*QuoteRequest_Post)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_booking_proto_rawDesc), len(file_booking_proto_rawDesc)),
			NumEnums:      5,
			NumMessages:   31,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_booking_proto_goTypes,
		DependencyIndexes: file_booking_proto_depIdxs,
		EnumInfos:         file_booking_proto_enumTypes,
		MessageInfos:      file_booking_proto_msgTypes,
	}.Build()
	File_booking_proto = out.File
	file_booking_proto_goTypes = nil
	file_booking_proto_depIdxs = nil
}
