# name: Pre Commit Checks
# on: [workflow_dispatch]

name: Pre Commit Checks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  golangci-lint:
    name: Lint Go code in ${{ matrix.module }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        module:
          - api-gateway
          - services/account
          - services/admin
          - services/booking
          - services/employee
          - services/inventory
          - services/notification
          - services/payment

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.11'

      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Run golangci-lint in ${{ matrix.module }}
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          args: --timeout=5m --out-format=colored-line-number
          working-directory: ${{ matrix.module }}
